src/lib/components/Charts/LimitDropdown.svelte
src/lib/components/Charts/Sankey.svelte
src/lib/components/Contracts/CodeViewer.svelte
src/lib/components/Header/HomeStatsSection.svelte
src/lib/components/Header/OtherStatsSection.svelte
src/lib/pages/Accounts/TopAccounts.svelte

https://app.clickup.com/t/2395238/OCCHIO-6476

fix NaN Header instances

---

src/lib/pages/SignInPage.svelte

https://app.clickup.com/t/2395238/OCCHIO-6555

Page scaling alignments

---

src/lib/components/Other/DelegateDetails/DelegateStepFour.svelte
src/lib/components/Other/DelegateDetails/DelegateStepOne.svelte
src/lib/components/Other/DelegateDetails/DelegateStepThree.svelte
src/lib/components/Other/DelegateDetails/DelegateStepTwo.svelte
src/lib/components/Other/TransferDetails/TransferStepFour.svelte
src/lib/components/Other/TransferDetails/TransferStepOne.svelte
src/lib/components/Other/TransferDetails/TransferStepThree.svelte
src/lib/components/Other/TransferDetails/TransferStepTwo.svelte
src/lib/components/Other/UndelegateDetails/UndelegateStepFour.svelte
src/lib/components/Other/UndelegateDetails/UndelegateStepOne.svelte
src/lib/components/Other/UndelegateDetails/UndelegateStepThree.svelte
src/lib/components/Other/UndelegateDetails/UnelegateStepTwo.svelte

https://app.clickup.com/t/2395238/OCCHIO-6556

fix: copy-icon sizes

---

src/lib/sections/HomePage/LatestBlocks.svelte
src/lib/sections/HomePage/TopValidators.svelte

https://app.clickup.com/t/2395238/OCCHIO-6590

fix: home tables alignment

---

src/lib/components/Charts/AreaChart.svelte
src/lib/components/Charts/ComboChart.svelte
src/lib/components/Charts/PoNegAreaChart.svelte
src/lib/components/Charts/Sankey.svelte
src/lib/components/Charts/StackedChart.svelte
src/lib/pages/Charts/ChartsPage.svelte

https://app.clickup.com/t/2395238/OCCHIO-6610

fix: x axis offset and responsiveness

---

src/lib/pages/Accounts/AccountDetails.svelte
src/lib/pages/Accounts/AccountTabs/EarningTab.svelte
src/lib/pages/Accounts/AccountTabs/TokensTab.svelte
src/lib/pages/Accounts/AccountTabs/TransactionsTab.svelte
src/lib/pages/Accounts/AccountTabs/TransferTab.svelte
src/lib/pages/Accounts/TopAccounts.svelte

https://app.clickup.com/t/2395238/OCCHIO-6605

add: empty state place holder to all tables

---

src/lib/components/TableData/Hash.svelte
src/lib/components/TableData/TxHash.svelte
src/lib/components/TableData/Validator.svelte
src/lib/pages/Blocks/index.svelte
src/lib/pages/Transactions/index.svelte
src/lib/sections/HomePage/TopValidators.svelte

https://app.clickup.com/t/2395238/OCCHIO-7341

fix: tooltips getting cutoff

---

src/lib/components/Reusables/Switch.svelte

https://app.clickup.com/t/2395238/OCCHIO-7342

fix: validator switch button paddings

---

src/lib/components/Reusables/TableSorter.svelte
src/lib/components/Reusables/Tooltip.svelte
src/lib/pages/Accounts/TopAccounts.svelte
src/lib/pages/Blocks/index.svelte
src/lib/pages/Transactions/index.svelte
src/lib/pages/Validators/index.svelte

https://app.clickup.com/t/2395238/OCCHIO-7344

add: deselect sorter when another is selected

---

src/lib/pages/Blocks/index.svelte

https://app.clickup.com/t/2395238/OCCHIO-7353

fix: table width

---

src/lib/components/Accounts/Overview.svelte
src/lib/components/Accounts/StakeInfo.svelte
src/lib/components/Validators/VerifiedBlocksTab.svelte
src/lib/pages/Accounts/AccountDetails.svelte
src/lib/pages/Blocks/BlockHash.svelte
src/lib/pages/Blocks/index.svelte
src/lib/pages/Transactions/TransactionHash/index.svelte
src/routes/__layout.svelte
src/utils/history.ts

https://app.clickup.com/t/2395238/OCCHIO-7350

fix: blocks breadcumb routing

---

src/lib/components/Paginator/index.svelte

https://app.clickup.com/t/2395238/OCCHIO-7366

fix: paginator "page 1/0"

---

src/lib/components/Charts/HomePageChart.svelte

https://app.clickup.com/t/2395238/OCCHIO-7155

add: homepage chart tooltip

---

src/lib/components/TableData/Validator.svelte
src/lib/pages/Contracts/index.svelte
src/lib/pages/Transactions/index.svelte

https://app.clickup.com/t/2395238/OCCHIO-7405

rework: contracts Page

---

src/lib/components/TableData/Validator.svelte
src/lib/pages/Contracts/ContractsPackageOverview.svelte
src/lib/pages/Contracts/Package.svelte
src/lib/pages/Contracts/PackageTabs/PackageDeploys.svelte
src/lib/pages/Contracts/PackageTabs/PackageGroups.svelte
src/lib/pages/Contracts/PackageTabs/PackageVersions.svelte
src/lib/pages/Contracts/index.svelte
src/routes/contract-package/[hash]/index.svelte
src/routes/uref/[hash]/index.svelte

https://app.clickup.com/t/2395238/OCCHIO-7406

Contract package page

---

src/lib/components/Header/Filter.svelte

https://app.clickup.com/t/2395238/OCCHIO-7465

fix: remove searchbar filter

---

src/lib/components/Other/DelegateDetails/DelegateStepOne.svelte
src/lib/components/Other/UndelegateDetails/UndelegateStepOne.svelte
src/lib/components/Other/ValidatorPicker.svelte
src/lib/components/Paginator/index.svelte

https://app.clickup.com/t/2395238/OCCHIO-7466

add: validatorPicker component

---

src/lib/components/TableData/CircleProgressBar.svelte
src/lib/pages/Validators/index.svelte

https://app.clickup.com/t/2395238/OCCHIO-7579
https://arcadia2.atlassian.net/browse/CAS-22?atlOrigin=eyJpIjoiZmM2ZTdlNDdjNWQxNGUzZGJjM2UwYmQ3MTFlMWMzMzgiLCJwIjoiaiJ9

fix: performance display

---

src/lib/components/Charts/EarningChart.svelte
src/lib/pages/Accounts/AccountTabs/EarningTab.svelte
src/utils/tooltip.ts

https://app.clickup.com/t/2395238/OCCHIO-7580
https://arcadia2.atlassian.net/browse/CAS-28?atlOrigin=eyJpIjoiZWE3ZjVmNzdhY2JiNDg1ZDg1YThjYzcyYjExMDRmMGMiLCJwIjoiaiJ9

fix: earning chart

---

src/utils/converters.ts

https://app.clickup.com/t/2395238/OCCHIO-7597

fix: negative time

---

src/lib/components/Reusables/Tooltip.svelte
src/lib/pages/Contracts/index.svelte
src/lib/pages/Validators/Auction.svelte
src/lib/pages/Validators/index.svelte

https://app.clickup.com/t/2395238/OCCHIO-7584
https://arcadia2.atlassian.net/browse/CAS-38?atlOrigin=eyJpIjoiNjU3NWVlZjRmNDRiNDM4Njk1MGI4NDA5ZjYwZWJiNWQiLCJwIjoiaiJ9
https://arcadia2.atlassian.net/browse/CAS-40?atlOrigin=eyJpIjoiYjY3ODgxOGMzYTIwNDY4Mzg2OGEwMWY4ZWM5Zjk4MmIiLCJwIjoiaiJ9

fix: contract and validator left tooltips
